export const Users = [
  {
    id: 1,
    profilePicture: "assets/jagannath.jpg",
    Username: "Jagannath",
  },
  {
    id: 2,
    profilePicture: "assets/alexa.jpg",
    Username: "Alexa",
  },
  {
    id: 3,
    profilePicture: "assets/christopher.jpg",
    Username: "Christopher",
  },
  {
    id: 4,
    profilePicture: "assets/Alice.jpg",
    Username: "Alice",
  },
  {
    id: 5,
    profilePicture: "assets/devika sharma.jpg",
    Username: "devika sharma",
  },
  {
    id: 6,
    profilePicture: "assets/natasha.jpg",
    Username: "Natasha",
  },
  {
    id: 7,
    profilePicture: "assets/kimson.jpg",
    Username: "Kimson",
  },
  {
    id: 8,
    profilePicture: "assets/stefan.jpg",
    Username: "Stefan",
  },
  {
    id: 9,
    profilePicture: "assets/sonia.jpg",
    Username: "Sonia",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/01.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    Comment: 17,
  },
  {
    id: 2,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/02.jpg",
    date: "1 hrs ago",
    userId: 2,
    like: 120,
    Comment: 68,
  },
  {
    id: 3,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/03.jpg",
    date: "25 mins ago",
    userId: 3,
    like: 230,
    Comment: 105,
  },
  {
    id: 4,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/04.jpg",
    date: "29 mins ago",
    userId: 4,
    like: 320,
    Comment: 170,
  },
  {
    id: 5,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/05.jpg",
    date: "50 mins ago",
    userId: 5,
    like: 363,
    Comment: 103,
  },
  {
    id: 6,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/06.jpg",
    date: "2 hrs ago",
    userId: 6,
    like: 202,
    Comment: 107,
  },
  {
    id: 7,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/14.jpg",
    date: "45 mins ago",
    userId: 7,
    like: 352,
    Comment: 57,
  },
  {
    id: 8,
    desc: "Love For All, Hearted For None",
    photo: "assets/post/08.jpg",
    date: "15 mins ago",
    userId: 8,
    like: 200,
    Comment: 70,
  },
];
